### ISSUE TITLE
b → false ?

### ISSUE THREAD

**Issue by znz** [ohmsha/programming-elixir-ja#3]
31ページの一番下の行に `!a` のコメントとして「a が truthy であれば false、そうでなければ b」とありますが、 `b` ではなく `false` ではないでしょうか?

**Comment by hisashim** [comment]
反応がたいへん遅くなりましたが、ご指摘ありがとうございます。

確認してみましたところ、
aがtruthyでない場合は（bでもfalseでもなく）trueになるように思います。
原文もそのように書かれています。

BasicTypes.pml:

>   !a      # false if a is truthy, otherwise true

念のためiexで試してみました。

>    iex(1)> a=nil; !a
>    true

そこで、訳者陣と相談のうえ、次のように変更することとなりました。

変更前

> ```
>  !a      # a が truthy であれば false、そうでなければ b
> ```

変更後

> ```
>  !a      # a が truthy であれば false、そうでなければ true
> ```

第2刷で反映されています。ご指摘に感謝します。
