### ISSUE TITLE
P195 lib/ ディレクトリ

### ISSUE THREAD

**Issue by ko1** [ohmsha/programming-elixir-ja#6]
> `server.ex` というファイルを、`sequence/` の `lib/` ディレクトリの中に加えよう。

これは、lib/ ディレクトリの sequence/。

原文

> Add the file `server.ex` to the `sequence/` directory under `lib`.

by 遠藤さん

**Comment by hisashim** [comment]
第2刷で次のように変更しました。ありがとうございます。

  * 変更前
    > server.ex というファイルを、sequence/ の lib/ ディレクトリの中に加えよう。

  * 変更後
    > server.ex というファイルを、lib/ の sequence/ ディレクトリの中に加えよう。
