### ISSUE TITLE
P249 Code.eval_quoted 

### ISSUE THREAD

**Issue by ko1** [ohmsha/programming-elixir-ja#7]
> Code.eval_quoted が説明なく現れていて驚きました。
> （先の 256 ページに説明はありました）

by 遠藤さん

まぁ、7ページくらい我慢して、... くれないかなぁ。

**Comment by hisashim** [comment]
第2刷で次のように補いました。ありがとうございます。

  * 変更前
    > このコードについて考えよう。

  * 変更後
    > このコードについて考えよう（Code.eval_quotedについてはあとで改めて説明する(p. 254)）。
