### ISSUE TITLE
P236 アナグラムのコード

### ISSUE THREAD

**Issue by ko1** [ohmsha/programming-elixir-ja#8]
> ●236 ページ下から 5 行目
> 
> 「アナグラムのコードを...書き直してみよう」ですが、
> アナグラムのコードってどこかにありましたっけ？

by 遠藤さん

原文から無さそう。

**Comment by hisashim** [comment]
p. 236の「アナグラムのコード」が指しているのは、p. 112の練習問題StringsAndBinaries-2かと思います。

原書p. 116

> Exercise: StringsAndBinaries-2
> Write an anagram?(word1, word2) that returns true if its parameters are anagrams.

日本語版p. 112

> 練習問題：StringsAndBinaries - 2
> パラメータがアナグラムだったらtrue を返すanagram?(word1, word2)
> という関数を書いてみよう。

これについては、訳者陣との相談の結果、p. 236を次のように変更することになりました。

変更前：

> アナグラムのコードをタスクとエージェントの両方を使って書き直してみよう。

変更後：

> ある単語のアナグラムを求めるプログラムを、タスクとエージェントの両方を使って書いてみよう。

第2刷で反映されています。ご指摘ありがとうございます。
