### ISSUE TITLE
P204 コールバックの数

### ISSUE THREAD

**Issue by ko1** [ohmsha/programming-elixir-ja#9]
> これも原著からの間違いかもしれませんが、
> コールバック関数「6 個」と言われているけれど
> 数えたら 7 個あるような？

by 遠藤さん

`format_status` を数えるかどうかだと思うんだけど、どうなんだろ。

**Comment by ko1** [comment]
Erlang の OTP 的には６個で、その数を述べている、ということで、７個並んでいる内の１つは format_status って感じで、とりあえずそのままにしようと思います。

**Comment by hisashim** [comment]
（備忘のためinvalidラベルを付けましたが、ご指摘には感謝しています。）
